import { TimelineEvent, TouristPlace, Itinerary, CulinaryItem, UrduPhrase } from "./types";

// Dynamic generated images from AI Studio
const IMAGES = {
  hunza: "/src/assets/images/pakistan_hero_hunza_1781247088392.jpg",
  badshahi: "/src/assets/images/lahore_badshahi_mosque_1781247109043.jpg",
  attabad: "/src/assets/images/attabad_lake_1781247126157.jpg",
  faisal: "/src/assets/images/faisal_mosque_1781247145872.jpg",
};

export const timelineEvents: TimelineEvent[] = [
  {
    year: "3300 BCE – 1300 BCE",
    title: "Indus Valley Civilization",
    titleUrdu: "وادی سندھ کی تہذیب",
    description: "One of the world's earliest major urban sanctuaries flourished at Mohenjo-daro and Harappa, pioneering modern sanitation, planned brick architecture, and metal industries.",
    descriptionUrdu: "دنیا کی قدیم ترین شہری تہذیبوں میں سے ایک جو موہنجوداڑو اور ہڑپہ کے مقام پر پروان چڑھی، جس نے جدید نکاسی آب اور فنِ تعمیر کو متعارف کرایا۔",
    category: "ancient",
  },
  {
    year: "500 BCE – 1000 CE",
    title: "Gandhara Buddhist Empire",
    titleUrdu: "گندھارا سلطنت",
    description: "Centering in Taxila and Peshawar, Gandhara was a global nexus of Buddhist philosophy, Grecian-hybrid art, craftsmanship, and ancient universities hosting scholarly exchange.",
    descriptionUrdu: "ٹیکسلا اور پشاور کے ارد گرد قائم گندھارا آرٹ، فلسفہ اور بدھ مت کا ایک عالمی گہوارہ تھا، جہاں قدیم یونیورسٹیوں میں یونانی و مقامی علوم سکھائے جاتے تھے۔",
    category: "ancient",
  },
  {
    year: "1526 – 1857 CE",
    title: "The Golden Mughal Era",
    titleUrdu: "مغلیہ دور حکومت",
    description: "An age of majestic architectural marvels, royal gardens, and multi-cultural flourishment. Masterpieces like Lahore Fort, Badshahi Mosque, and Shalimar Gardens were raised.",
    descriptionUrdu: "عظیم الشان تعمیرات، باغات اور ثقافت کا سنہرا دور۔ لاہور کا قلعہ، بادشاہی مسجد اور شالامار باغ اسی دورِ عالیہ کے شاہکار ہیں۔",
    category: "colonial",
  },
  {
    year: "August 14, 1947",
    title: "Independence of Pakistan",
    titleUrdu: "قیامِ پاکستان",
    description: "Following a historic freedom struggle led by Quaid-e-Azam Muhammad Ali Jinnah and envisioned by poet-philosopher Allama Iqbal, the sovereign state of Pakistan was born.",
    descriptionUrdu: "قائد اعظم محمد علی جناح کی قیادت اور علامہ اقبال کے خواب کے نتیجے میں، ایک خود مختار وطن کی حیثیت سے دنیا کے نقشے پر پاکستان کا ظہور ہوا۔",
    category: "independence",
  },
  {
    year: "Present Day",
    title: "Modern Tourism Peak",
    titleUrdu: "جدید سیاحت اور ثقافت",
    description: "Pakistan opens its gates to the world, consistently ranking as a top global adventure tourism destination due to its high mountain scaling routes and breathtaking hospitality.",
    descriptionUrdu: "پاکستان نے سیاحت کے لیے اپنے دروازے کھولے، اور اپنے بلند و بالا پہاڑوں اور روایتی مہمان نوازی کی بدولت دنیا کی بہترین ایڈونچر ٹورازم منزلوں میں شمار ہونے لگا۔",
    category: "modern",
  },
];

export const touristPlaces: TouristPlace[] = [
  {
    id: "hunza-valley",
    name: "Hunza Valley",
    nameUrdu: "وادیء ہنزہ",
    region: "Northern Highlands",
    province: "Gilgit-Baltistan",
    description: "A gorgeous mountainous valley surrounded by snow-draped peaks, famous for its emerald lakes, ancient watchtowers, and long-lived culture.",
    descriptionUrdu: "برف پوش پہاڑی چوٹیوں میں گھری ایک خوبصورت وادی، جو اپنے فیروزی دریاؤں، تاریخی قلعوں اور طویل المعیاد صحت مند ثقافت کے لیے مشہور ہے۔",
    longDescription: "Framed by the majestic Rakaposhi, ultramarine landscapes, and historic watchtowers (Altit and Baltit Forts), Hunza Valley is the crown jewel of Gilgit-Baltistan tourism. The residents are celebrated for their warmth, vibrant literary rates, and rich festive traditions. The spectacular apricot blossoms in spring turn the entire valley into a pink fairytale.",
    longDescriptionUrdu: "عظیم راکاپوشی پہاڑ، آسمانی رنگ کے نظاروں اور التت و بلتت قلعوں کے حسین سنگم پر واقع وادی ہنزہ گلگت بلتستان کا تاج ہے۔ یہاں کی عوام اپنی بے مثال مہمان نوازی اور متحرک ثقافت کے لیے جانی جاتی ہے۔ موسم بہار میں خوبانی کے شگوفے پوری وادی کو ایک دلکش گلابی جنت میں بدل دیتے ہیں۔",
    imageUrl: IMAGES.hunza,
    bestSeason: "April to October (Spring and Autumn are legendary)",
    entryFee: "Free (Fort tickets: ~Rs. 1000 for foreigners, Rs. 200 for locals)",
    accessibility: "Mainly via Karakoram Highway by road, or flights to Gilgit followed by a scenic drive.",
    highlights: ["Baltit & Altit Forts", "Karimabad Bazaar", "Eagle’s Nest Sunset point", "Passu Cones view"],
    tags: ["Highlands", "Adventure", "History", "Nature"],
  },
  {
    id: "badshahi-mosque",
    name: "Badshahi Mosque, Lahore",
    nameUrdu: "بادشاہی مسجد، لاہور",
    region: "Cultural Heartland",
    province: "Punjab",
    description: "The magnificent heart of Lahore, representing the absolute pinnacle of Mughal sandstone and marble craftsmanship.",
    descriptionUrdu: "لاہور کا شان دار ثقافتی مرکز، جو مغل فنِ تعمیر اور سرخ پتھر کی نقاشی کا ایک لاجواب اور لازوال نمونہ ہے۔",
    longDescription: "Commissioned by Emperor Aurangzeb in 1671, the Badshahi Mosque was the largest mosque in the world for over 300 years. Built with rich red sandstone from Rajasthan and inlaid with precious white marble calligraphy, it accommodates up to 100,000 worshippers. Positioned next to the Lahore Fort and the vibrant walled city, it glows with imperial majesty.",
    longDescriptionUrdu: "شاہی مغل حکمران اورنگزیب عالمگیر کی زیرِ سرپرستی ۱۶۷۱ میں تعمیر ہونے والی بادشاہی مسجد صدیوں تک دنیا کی سب سے بڑی مسجد کے اعزاز سے سرفراز رہی۔ سرخ پتھر اور سنگِ مرمر کی نفیس کاریگری والے اس شاہکار میں ایک لاکھ نمازیوں کی گنجائش ہے۔ یہ قلعہ لاہور کے متصل واقع ہوکر رعب و دبدبے کا منظر پیش کرتی ہے۔",
    imageUrl: IMAGES.badshahi,
    bestSeason: "October to March (Pleasant, cool historic walks)",
    entryFee: "Free entry for all",
    accessibility: "Located in central Lahore, easily accessible by Metrobus, private cabs, or walking tours of the old city.",
    highlights: ["Imperial Mughal Gateway", "Intricate Marble Calligraphy", "Tomb of Allama Iqbal", "Adjacent Lahore Fort"],
    tags: ["Mughal Heritage", "Architecture", "Sacred", "Culture"],
  },
  {
    id: "attabad-lake",
    name: "Attabad Lake",
    nameUrdu: "عطا آباد جھیل",
    region: "Northern Highlands",
    province: "Gilgit-Baltistan",
    description: "An stunningly beautiful turquoise-blue lake formed after a massive landslide, offering boating, jet skiing, and grand cliff views.",
    descriptionUrdu: "مٹی کا تودہ گرنے کے بعد وجود میں آنے والی گہری فیروزی رنگ کی جھیل، جو اب واٹر اسپورٹس اور کشتی رانی کا اہم ترین مرکز ہے۔",
    longDescription: "Born out of natural drama in 2010 due to a massive landslide, Attabad Lake has transformed into one of Pakistan's most spectacular nature magnets. Its surreal bright blue color is a result of glacial flour (silt) suspended in the pure mountain run-off. Renting a motorboat, kayaking of the tranquil waters, or taking a jet ski between high canyon walls is highly inspiring.",
    longDescriptionUrdu: "۲۰۱۰ میں مٹی کا ایک بہت بڑا تودہ گرنے کے بعد بننے والی عطا آباد جھیل اب پاکستان کی مشہور ترین تفریحی جھیلوں میں شامل ہے۔ اس کے چمکدار گہرے فیروزی مٹیالی رنگ کی وجہ وہ گلیشائری معدنیات ہیں جو صاف پانی میں تحلیل ہوتی ہیں۔ بلند وبالا پہاڑی دیواروں کے درمیان کشتی رانی اور جیٹ اسکیئنگ کا تجربہ حیرت انگیز معلوم ہوتا ہے۔",
    imageUrl: IMAGES.attabad,
    bestSeason: "May to September (Brilliant sunshine, warm breeze)",
    entryFee: "Boating & Jet-ski rates range from Rs. 1,000 to Rs. 4,000",
    accessibility: "Located along the Karakoram Highway, approximately 30 minutes drive from Hunza Karimabad.",
    highlights: ["Turquoise Boat Rides", "Lakeside Glamping", "Jet Skiing", "Passu Cones Backdrop"],
    tags: ["Water Sports", "Scenic", "Nature", "Lakes"],
  },
  {
    id: "faisal-mosque",
    name: "Faisal Mosque, Islamabad",
    nameUrdu: "فیصل مسجد، اسلام آباد",
    region: "Northern Highlands",
    province: "Islamabad Capital Territory",
    description: "The majestic national mosque representing a Bedouin tent design, set against the Margalla Hills of Islamabad.",
    descriptionUrdu: "اسلام آباد کی خوبصورت قومی مسجد، جو ایک خوبصورت صحرائی خیمے کی طرز پر تیار کی گئی ہے اور پسِ منظر میں مارگلہ کی سرسبز پہاڑیاں ہیں۔",
    longDescription: "An architectural marvel designed by Turkish architect Vedat Dalokay, the Faisal Mosque breaks away from traditional domes and features an eight-sided concrete shell mimicking a Bedouin tent, surrounded by four 88-meter thin minarets. Endowed by King Faisal of Saudi Arabia, its interior is highlighted by the grand gold-plated Turkish chandelier.",
    longDescriptionUrdu: "ترکی کے نامور آرکیٹیکٹ ویدات دالوکے کی ڈیزائن کردہ یہ مسجد گنبد کے روایتی سائز سے ہٹ کر بنائی گئی ہے۔ یہ ایک آٹھ کونوں والے خیمے کی صورت رکھتی ہے جس کے گرد ۸۸ میٹر بلند خوبصورت مینار چمکتے ہیں۔ سعودی فرمانروا شاہ فیصل کے تعاون سے تعمیر شدہ اس کے ہال میں جڑا سنہرا جھومر دیکھنے کے لائق ہے۔",
    imageUrl: IMAGES.faisal,
    bestSeason: "Year-Round (Best viewed at sunset or late afternoon)",
    entryFee: "Free entry for all worshippers & respectful visitors",
    accessibility: "Situated at the foothills of Margalla at the end of Faisal Avenue, reachable within minutes from any city sector.",
    highlights: ["Bedouin Tent Concept", "Turkish Chandelier", "Outdoor Marble Esplanades", "Sadequain’s Masterful Calligraphy"],
    tags: ["Modern Arts", "Islamabad Landmark", "Scenic", "Spiritual"],
  },
  {
    id: "mohenjo-daro",
    name: "Mohenjo-daro",
    nameUrdu: "موہنجوداڑو",
    region: "Ancient Sindh",
    province: "Sindh",
    description: "The 5,000-year-old remnant city of the Bronze Age, depicting the supreme heights of prehistoric planning.",
    descriptionUrdu: "پانچ ہزار سالہ قدیم کانسی کے دور کا ایک تاریخی شہر، جو زمانہ تاریخ قبلِ مسیح میں شہری طرزِ زندگی کی منصوبہ بندی کا بے نظیر ثبوت ہے۔",
    longDescription: "Dating back to 2500 BCE, Mohenjo-daro ('Mound of the Dead Men') is a UNESCO World Heritage site and the grand epicenter of the Indus Valley Civilization. Long before Rome or Athens, are archaeological triumphs of grid-aligned streets, brick drainage structures, individual hot wells, and the famous 'Great Bath' municipal pool. An absolute must-visit for historical scholars.",
    longDescriptionUrdu: "ہمارے عہد سے پچیس سو سال قبل مسیح آباد ہونے والا موہنجوداڑو یونیسکو کے عالمی ثقافتی ورثے کا مستقل حصہ ہے۔ روم اور ایتھنز کی آبادیوں سے بہت پہلے یہاں منظم مکانات، پختہ اینٹوں کی گلیاں، زیرِ زمین نالیاں اور سب سے بڑا عوامی غسل خانہ (گریٹ باتھ) تعمیر کیا جاچکا تھا، جو کہ قدیم انجینئری کا ثبوت ہے۔",
    imageUrl: "https://picsum.photos/id/1015/800/600", // Fallback high quality nature/terrain landscape
    bestSeason: "November to February (Avoid high summer heat)",
    entryFee: "Rs. 50-100 for locals, Rs. 1000 for foreigners",
    accessibility: "Located near Larkana, Sindh. Accessible via domestic flights to Mohenjo-daro Airport or by train and road routes.",
    highlights: ["The Great Bath", "Sleek Brick Grid Streets", "Mohenjo-daro Museum", "Priest-King Statuette site"],
    tags: ["Archeology", "Ancient Ruins", "Indus History", "World Heritage"],
  },
  {
    id: "fairy-meadows",
    name: "Fairy Meadows & Nanga Parbat",
    nameUrdu: "فیری میڈوز اور نانگا پربت",
    region: "Northern Highlands",
    province: "Gilgit-Baltistan",
    description: "Grass meadows with alpine cabins, looking directly onto the massive 8,126m Killer Mountain, Nanga Parbat.",
    descriptionUrdu: "پائن کے جنگلات سے گھرا ایک خوبصورت سرسبز میدان، جہاں سے دنیا کی نویں بلند ترین گراں مایہ چوٹی 'نانگا پربت' کا پورا رعب واضح دکھائی دیتا ہے۔",
    longDescription: "Named by German climber climbers as 'Märchenwiese' (Fairy Meadows), this alpine meadow is a remote heaven accessible via a hair-raising jeep track followed by a trek. It sits right at the foot of Nanga Parbat, the 9th highest peak in the world. Visitors stay in sweet wooden cabins, wake up to glacier-fed lakes, and watch golden sunbeams strike the massive block of ice peaks.",
    longDescriptionUrdu: "جرمن کوہ پیماؤں کی طرف سے 'پریوں کا چراگاہ' پکارا جانے والا فیری میڈوز ایک سحر انگیز میدان ہے۔ یہاں تک پہنچنے کے لیے ایک ایڈونچر سے بھرے کچے جیپ ٹریک اور پھر پیدل ٹریکنگ کرنی ہوتی ہے۔ یہ مقام برف کے عظیم دیو نانگا پربت (۸،۱۲۶ میٹر) کے سائے میں بسا ہے۔ یہاں لکڑی کے ہٹس اور کیمپنگ کا انوکھا لطف حاصل ہوتا ہے۔",
    imageUrl: "https://picsum.photos/id/1043/800/600", // Forest/mountain fallback
    bestSeason: "June to August (Pleasant hiking weather)",
    entryFee: "Jeep charter: Rs. 10,000 to Rs. 15,000 (shared)",
    accessibility: "Jeep ride from Raikot Bridge on Karakoram Highway, followed by a 2-3 hour trek under pine canopies.",
    highlights: ["Nanga Parbat Basecamp trek", "Reflections Lake camps", "Chilghoza Pine Forests", "Bonfire Star Gazing"],
    tags: ["Hiking", "Trekking", "Camping", "Extreme Adventure"],
  },
  {
    id: "swat-valley",
    name: "Swat Valley",
    nameUrdu: "وادیء سوات",
    region: "Khyber Pass",
    province: "Khyber Pakhtunkhwa",
    description: "Often called 'The Switzerland of the East,' celebrated for its roaring river, trout fisheries, and ancient Buddhist relics.",
    descriptionUrdu: "پانی کے شاندار جھرنوں، سدا بہار حسن اور بدھ مت کے نوادرات کی وجہ سے اسے مشرق کا 'سوئٹزرلینڈ' بھی کہا جاتا ہے۔",
    longDescription: "Swat Valley is a historical valley of staggering beauty. It features lush orchards of peaches, gushing glacial rivers perfect for white-water rafting, and the iconic Malam Jabba resort for winter skiing. Swat was once the center of Uddiyana Buddhism and retains exquisite rock-carved Buddhas and archaeological mounds built across centuries.",
    longDescriptionUrdu: "وادی سوات بے شمار حسین نظاروں کی سرزمین ہے۔ شفتالو اور مٹھاس بھرے پھلوں کے باغات، موج مارتے دریا اور مالم جبہ کا تفریحی اسکیئنگ ریزورٹ اس کی پہچان ہیں۔ ماضی میں یہ بدھ مت کے مقتدر مراکز میں شامل تھا اور اج بھی اس کے پہاڑوں پر قدیم نقوش تراشے پائے جاتے ہیں۔",
    imageUrl: "https://picsum.photos/id/1036/800/600", // Beautiful lake stream fallback
    bestSeason: "April to October (Pleasant sightseeing) / Jan to Feb (Skiing in Malam Jabba)",
    entryFee: "Free entry to most sites",
    accessibility: "Smoothly accessible from Islamabad via Swat Motorway M-16 (about 3 hours drive).",
    highlights: ["Malam Jabba Ski Resort", "Kalam Forest & Ushu Valley", "Mahodand Alpine Lake", "Swat Archaeological Museum"],
    tags: ["Family", "Skiing", "Scenic Rivers", "Gardens"],
  },
  {
    id: "hingol-national-park",
    name: "Hingol National Park",
    nameUrdu: "ہنگول نیشنل پارک",
    region: "Balochistan Coast",
    province: "Balochistan",
    description: "A mesmerizing lunar-like desert landscape with unique rock shapes like the 'Princess of Hope' and natural mud volcanoes.",
    descriptionUrdu: "چاند جیسی بناوٹ والی ایک دلفریب صحرائی پٹی، جہاں ہواؤں کے تھپیڑوں سے بنے قدرتی مجسمے جیسے 'امید کی شہزادی' اور منفرد مٹی کے آتش فشاں واقع ہیں۔",
    longDescription: "As Pakistan’s largest national park, Hingol borders the Makran Coastal Highway, offering a visual masterclass of golden canyons, mud volcanoes, and wind-sculpted rock towers. Key sights include the 'Princess of Hope' (named by Angelina Jolie due to its majestic standing post) and the sacred Hinglaj Mata Temple cave. It is an unexplored frontier of raw beauty.",
    longDescriptionUrdu: "یہ پاکستان کا سب سے بڑا قدرتی پارک ہے جو مکران کوسٹل ہائی وے کے ساتھ پھیلا ہوا ہے۔ یہاں کے سنہری غار، مٹی کے دانے دار آتش فشاں اور ہوائی کٹاؤ سے تراشیدہ چٹانیں سیاحوں کو حیران کرتی ہیں۔ ہالی ووڈ اسٹار انجلینا جولی کا 'پرنسس آف ہوپ' نام دیا گیا مجسمہ اور قدیم مائی ہنگلاج کا غار نما مندر بھی یہیں ہیں۔",
    imageUrl: "https://picsum.photos/id/1018/800/600", // Canyons/terrain landscape fallback
    bestSeason: "November to February (Cool coastal breezes)",
    entryFee: "Free wildlife reserve access",
    accessibility: "Easily reachable by road from Karachi (approximately 3 to 4 hours scenic coastal drive along the highway).",
    highlights: ["Princess of Hope Statue", "Sphinx of Balochistan", "Hingol River Estuary", "Chandragup Mud Volcanoes"],
    tags: ["Road Trip", "Coastal Sands", "Scenic Canyons", "Geological"],
  }
];

export const itineraries: Itinerary[] = [
  {
    id: "karakoram-scenic",
    title: "The Ultimate Karakoram Scenic Highway Adventure",
    titleUrdu: "شاہراہِ قراقرم کے حسین نظارے",
    theme: "scenic",
    duration: 5,
    overview: "A majestic slow journey starting from Islamabad, crossing deep valleys to reach the pure serenity of Hunza Karimabad and Attabad Lake.",
    overviewUrdu: "سرسبز اسلام آباد سے شروع ہو کر، بلند ترین پہاڑوں کا سینہ چیرتی ہوئی، ہنزہ کریم آباد اور عطا آباد جھیل کے شفاف وادیوں تک کا ایک ناقابل فراموش سفر۔",
    items: [
      {
        day: 1,
        title: "Departure & Abbottabad Foothills",
        titleUrdu: "روانگی اور ایبٹ آباد کا طواف",
        description: "Depart from Islamabad. Travel via Hazara Motorway, viewing terraced farms and deep mountains. Stop for a traditional meal in Abbottabad.",
        descriptionUrdu: "اسلام آباد سے روانگی۔ ہزارہ موٹروے پر حسین پہاڑوں کے نظارے۔ روایتی ظہرانہ اور ایبٹ آباد کے گرد خوشگوار آب و ہوا کا مشاہدہ۔",
        activities: ["Scenic highway drive", "Chilas junction stop", "Night at Riverside Hotel in Besham"],
      },
      {
        day: 2,
        title: "Karakoram Highway and Mountain Junctions",
        titleUrdu: "شاہراہِ قراقرم اور تین پہاڑوں کا سنگم",
        description: "Drive north along the roaring Indus River on the Indus highway. Visit the point where three grand mountain ranges meet (Karakoram, Himalaya, Hindu Kush).",
        descriptionUrdu: "دریا نے سندھ کے شور مچاتے لہروں کے ساتھ شمال کی طرف پیش قدمی۔ اس پروقار موڑ پر رکنا جہاں ہمالیہ، قراقرم اور ہندوکش ایک ساتھ ملتے ہیں۔",
        activities: ["Three Ranges Meeting Point photoshoot", "View of Gilgit River", "Arrival in Karimabad, Hunza"],
      },
      {
        day: 3,
        title: "The Forts of Hunza & Eagle's Nest Sunset",
        titleUrdu: "ہنزہ کے قلعے اور عقاب کے گھونسلے سے غروبِ آفتاب",
        description: "Explore the 800-year-old Baltit Fort and the 1100-year-old Altit Fort. Watch the sunset illuminate Rakaposhi from Eagle's Nest.",
        descriptionUrdu: "ہنزہ کے شاہی خاندان کے آٹھ سو سالہ پرانے بلتت قلعے کی سیر۔ سورج ڈوبنے کے وقت راکاپوشی پہاڑی کے جادوئی نظارے۔",
        activities: ["Baltit Fort Tour", "Apricot Juice tasting", "Eagle's Nest high-point photography"],
      },
      {
        day: 4,
        title: "Attabad Turquoise Waters & Passu suspension Bridge",
        titleUrdu: "عطا آباد جھیل اور ہنگامی معلق پل کا غبار",
        description: "Travel to Attabad Lake. Ride a classic wooden boat on the turquoise waters. Visit the steep hanging Passu suspension bridge and gorgeous cones peak.",
        descriptionUrdu: "فیروزی عطا آباد جھیل پر کشتی رانی اور تصاویر۔ خوفناک حد تک خوبصورت معلق پاسو پل اور چٹانی نوکدار پاسو کونز کا دلفریب منظر۔",
        activities: ["Boat safari in Attabad Lake", "Husseini Suspension Bridge walk", "Local organic cuisine dinner"],
      },
      {
        day: 5,
        title: "Journey Back with Eternal Souvenirs",
        titleUrdu: "یادگاروں کے ساتھ واپس روانگی",
        description: "Drive back along Karakoram highway towards Islamabad, gathering local rugs, gemstones, and dried fruits from the market.",
        descriptionUrdu: "مقامی شالیں، خشک میوہ جات اور ہنزہ کے قیمتی پتھر بطور تحفہ ساتھ سمیٹ کر شاہراہِ قراقرم سے اسلام آباد واپسی کا سفر۔",
        activities: ["Karimabad shopping bazaar", "Long driving playlist and memories sharing", "Arrival at airport"],
      }
    ]
  },
  {
    id: "punjab-cultural",
    title: "Punjab Imperial Heritage and Mughal Splendor",
    titleUrdu: "پنجاب کے مغلیہ دور کا شاہی سفر",
    theme: "cultural",
    duration: 3,
    overview: "An immersive historical retreat exploring Sufi arches, grand gardens, Mughal fortifications, and the intense culture of Lahore.",
    overviewUrdu: "لاہور کے پرانے بازاروں، صوفیانہ درگاہوں، اور مغلیہ دور کی مضبوط فصیلوں کے درمیان رچے بسے بے پناہ جذبے کا دو روزہ تفصیلی سفر۔",
    items: [
      {
        day: 1,
        title: "Arrival in Lahore and Sufi Qawwali Evening",
        titleUrdu: "لاہور آمد اور صوفیانہ محفل",
        description: "Arrive in Lahore. Settle in the hotel. In the evening, visit a historic shrine to witness enchanting local Sufi dervish dance and music.",
        descriptionUrdu: "زندہ دلانِ لاہور آمد۔ ہوٹل میں قیام۔ شام کے وقت صوفی درگاہ پر روحانی قوالی کا سماں اور دھمال کے روایتی مناظر کا مشاہدہ۔",
        activities: ["Arrival & local greeting", "Lahore Museum tour", "Sufi shrine Qawwali evening"],
      },
      {
        day: 2,
        title: "The Old Walled City, Fort and Badshahi Mosque",
        titleUrdu: "پرانی دیواروں کا شہر، شاہی قلعہ اور بادشاہی مسجد",
        description: "Walk inside Delhi Gate to standard Mughal baths (Shahi Hammam). Explore the majestic Lahore Fort (Shahi Qila) and the Badshahi Mosque.",
        descriptionUrdu: "پرانے دلی دروازے کے اندر تعمیر مغلوں کے شاہی حمام کا دورہ۔ شاہی قلعے کے شیش محل کی چمک کا نظارہ اور بادشاہی مسجد کی خوبصورتی۔",
        activities: ["Walled City historic walk", "Sheesh Mahal mirrored palace", "Dinner at famous Lahore Food Street next to minarets"],
      },
      {
        day: 3,
        title: "Wagah Border Ceremony & Shalimar Gardens",
        titleUrdu: "واہگہ بارڈر پریڈ اور شالامار باغ",
        description: "Walk under the cooling water fountains of Shalimar Gardens. In the afternoon, attend the energetic flag-lowering parade at the Wagah Border.",
        descriptionUrdu: "شاہجہانی شالامار باغ کے تینوں درجوں کی سیر۔ سہ پہر کو واہگہ بارڈر پر جوش و خروش سے بھرپور ملی نغموں کی گونج میں پرچم اتارنے کی منفرد پریڈ۔",
        activities: ["Shalimar Gardens picnic", "Wagah Border nationalistic flag parade", "Depart with sweets"],
      }
    ]
  }
];

export const culinaryItems: CulinaryItem[] = [
  {
    name: "Siri Paye",
    nameUrdu: "سری پائے",
    category: "mains",
    description: "A slow-cooked stew of cow or goat trotters and skull with a rich, gelatinous spiced broth. An ultimate breakfast food, often eaten with fresh hot Naan bread.",
    descriptionUrdu: "بکرے یا گائے کے سر اور پائے کے ساتھ ہلکی آنچ پر گھنٹوں پکا ہوا مصالحہ دار لذیذ سالن۔ اسے عموماً صبح ناشتے میں خمیری روٹی کے ساتھ کھایا جاتا ہے۔",
    imageUrl: "https://picsum.photos/seed/paye/400/300",
    flavorProfile: "Rich, deeply savory, gelatinous and highly spiced",
  },
  {
    name: "Lahori Biryani",
    nameUrdu: "لاہوری بریانی",
    category: "mains",
    description: "Fragrant basmati rice cooked layered with spiced chicken curry, potatoes, saffron water, fresh mint leaves, and sliced lemons.",
    descriptionUrdu: "زعفران، پودینہ اور تیکھے مصالحہ دار مرغ کے سالن کے ساتھ تہہ بہ تہہ پکے ہوئے باسمتی چاولوں کا شاندار اور مقبول ترین شاہکار۔",
    imageUrl: "https://picsum.photos/seed/biryani/400/300",
    flavorProfile: "Incredibly aromatic, spicy, fruity and robust",
  },
  {
    name: "Kashmiri Chai (Pink Tea)",
    nameUrdu: "کشمیری چائے",
    category: "beverage",
    description: "A traditional pink-colored milk tea brewed from green leaves, sea salt, milk, baking soda, and garnished with chopped pistachios and almonds.",
    descriptionUrdu: "سبز چائے کے مخصوص پتوں، بیکنگ سوڈا، نمک اور دودھ کے ابال سے گلابی مائل بنائی گئی فرحت بخش نمکین یا میٹھی چائے۔ پستہ اور بادام سے سجائی جاتی ہے۔",
    imageUrl: "https://picsum.photos/seed/pinktea/400/300",
    flavorProfile: "Creamy, nutty, slightly salty and heart-warming",
  },
  {
    name: "Balochi Sajji",
    nameUrdu: "بلوچی سجی",
    category: "mains",
    description: "A native skewered whole lamb or chicken marinated in local rock salt, skewered on wood logs, and slow-roasted over charcoal flames to perfect tenderness.",
    descriptionUrdu: "سالم مرغ یا بکرے پر ہلکا نمک لگا کر لکڑی کی سلاخ پر انگاروں کے ارد گرد دھیمی آنچ پر دیسی انداز میں بھنا ہوا گوشت جو نہایت نرمل اور جاندار ہوتا ہے۔",
    imageUrl: "https://picsum.photos/seed/sajji/400/300",
    flavorProfile: "Smoky, natural meat juice flavor, juicy and mildly salty",
  }
];

export const urduPhrases: UrduPhrase[] = [
  {
    phrase: "Khushamdeed",
    urdu: "خوش آمدید",
    romanUrdu: "Khush-am-deed",
    meaning: "Welcome",
    context: "Used to welcome guests to houses, cities, hotels, and tourist places.",
  },
  {
    phrase: "Shukriya",
    urdu: "شکریہ",
    romanUrdu: "Shuk-riya",
    meaning: "Thank you",
    context: "Sincere gratitude, used throughout daily communications with drivers or serving staff.",
  },
  {
    phrase: "Aap kaise hain?",
    urdu: "آپ کیسے ہیں؟",
    romanUrdu: "Aap kaise hain?",
    meaning: "How are you?",
    context: "Friendly polite query about someone’s health, suitable for everyone.",
  },
  {
    phrase: "Mehman-Nawazi",
    urdu: "مہمان نوازی",
    romanUrdu: "Mehman-nawazi",
    meaning: "Hospitality",
    context: "A central pillar of Pakistani culture meaning putting guests before self.",
  },
  {
    phrase: "Khuda Hafiz",
    urdu: "خدا حافظ",
    romanUrdu: "Khuda hafiz",
    meaning: "Goodbye / May God protect you",
    context: "The standard respectful departure phrase when farewell is given.",
  }
];
